### ISSUE TITLE
能够生成strm，但是无法获取链接

### ISSUE THREAD

**Issue by sucooer** [knifezred/123strm#3]
大佬看看我的配置哪里的问题，使用cd2挂载，不知道是不是pathPrefix填的不对，strm文件里链接不完整
```yaml
# 定时任务cron表达式，不配置则默认为每天凌晨1点执行
# 为防止冲突，所有job都使用一个corn，依次生成直到全部结束
cron: '0 2 * * *'
# strm地址使用官方下载链接
use302Url: True
# 不配置则默认不使用代理
proxy:
# 302链接缓存过期时间(秒)，默认5分钟
cacheExpireTime: 300
# strm路径前缀，可设置为cd2挂载的目录或者123盘webdav挂载的路径，需要加上对应设置的rootFolder的文件夹目录
# 如：选择的rootFolder为 /影视剧/电视剧，cd2映射的路径为 /volume1/docker/cloud_nas/123云盘
# 则pathPrefix为 /volume1/docker/cloud_nas/123云盘/影视剧/电视剧、
# use302Url=True时该设置无效
pathPrefix:
# 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
flatten_mode: False
# 是否下载字幕文件（可选，默认 False）
subtitle: True
# 是否下载图片文件（可选，默认 False）
image: True
# 是否下载 .nfo 文件（可选，默认 False）
nfo: True
# 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件，仅支持strm文件（可选，默认 False）
overwrite: False
# 视频文件最小限制，低于该大小的视频不处理，默认为100Mb
minFileSize: 104857600
# 程序启动后立即执行任务
runningOnStart: True
# https://www.123pan.com/developer 注册获取
clientID: ''
clientSecret: ''
# 输出路径
targetDir: '/media/'
# 以上所有设置均可在JobList中单独设置，优先使用JobList中的配置，没有的再使用默认值
# targetDir 为最终输出路径，JobList 中可以配置多个账号，每个账号可以配置多个文件夹，该配置必须为每个Job配置独立的文件夹，不能嵌套，不能相互包含，否则生成后会清空非Job配置获取的文件
JobList:
  - id: '日剧'
    rootFolderId: '12843142'
    targetDir: '/media/日剧'
    pathPrefix: '/mnt/123云盘/影视/电视剧/日剧/'
  - id: '电影'
    rootFolderId: '16067743'
    targetDir: '/media/电影'
    pathPrefix: '/mnt/123云盘/影视/电影/'
```

![image](https://img.pub/p/878a31c2dfb1005d0806.png)
